import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './style.css';
const money = (n: number) => `$${(n / 1e9).toFixed(4)}`;
function App() {
  const [state, setState] = useState<any>(), [error, setError] = useState(''), [busy, setBusy] = useState(''), [connected, setConnected] = useState(false);
  useEffect(() => { const events = new EventSource('/api/events'); events.onmessage = e => { setState(JSON.parse(e.data)); setConnected(true); }; events.onerror = () => setConnected(false); return () => events.close(); }, []);
  async function control(action: string) {
    if (action === 'reset' && !confirm('Archive this run and reset the world, supplies, inventories, and $1 budget?')) return;
    setBusy(action); setError('');
    try { const response = await fetch(`/api/control/${action}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ confirm: action === 'reset', runId: state.id }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setState(data); }
    catch (e: any) { setError(e.message); } finally { setBusy(''); }
  }
  if (!state) return <main><h1>House Arena</h1><p>Connecting to the local arena…</p></main>;
  const reserved = Object.values(state.reservations).reduce((a: number,b: any)=>a+b,0) as number;
  const done = state.tasks.filter((t: any)=>t.status==='done').length;
  return <main>
    <header><div><div className="eyebrow">MINECRAFT / THREE MINDS, ONE HOUSE</div><h1>House Arena<span>26.3</span></h1><p>A shared survival build. One dollar. Your front-row seat.</p></div><div className={`status ${state.status}`}><i/>{state.status}<small>{connected?'Live connection':'Reconnecting…'}</small></div></header>
    <section className="toolbar"><div className="controls">{['start','pause','resume'].map(action=><button key={action} className={action==='start'?'primary':''} disabled={!!busy || !connected || (action==='pause' ? state.status!=='running' : state.status==='running'||state.status==='complete')} onClick={()=>control(action)}>{busy===action?'Working…':action[0].toUpperCase()+action.slice(1)}</button>)}<button onClick={()=>control('overview')} disabled={!!busy}>Return to overview ↗</button><button className="danger" onClick={()=>control('reset')} disabled={!!busy}>Reset run</button></div><div className="server">Join as <strong>aryank1511</strong> · localhost:25565</div></section>
    {(error||state.reason)&&<div role="status" className={error?'notice error':'notice'}>{error||state.reason}</div>}
    <div className="metrics"><section><div className="label">RUN BUDGET</div><strong>{money(state.spent)} <em>/ ${state.limit.toFixed(2)}</em></strong><div className="meter"><b style={{width:`${Math.min(100,state.spent/(state.limit*1e9)*100)}%`}}/><i style={{width:`${Math.min(100,reserved/(state.limit*1e9)*100)}%`}}/></div><small>{money(reserved)} reserved for pending requests</small></section><section><div className="label">BUILD PROGRESS</div><strong>{done} <em>/ {state.tasks.length} sections</em></strong><div className="meter"><b style={{width:`${state.tasks.length?done/state.tasks.length*100:0}%`}}/></div><small>Verified against actual world blocks</small></section><section><div className="label">BLUEPRINT</div><strong>{state.blueprint?`${state.blueprint.design.width} × ${state.blueprint.design.depth}`:'Open canvas'}</strong><small>{state.blueprint?`${state.blueprint.approved?'Approved':'In review'} · ${state.blueprint.votes.length}/3 votes · revision ${state.blueprint.revision}`:'Agents will propose and review a design after Start'}</small></section></div>
    <div className="agents">{Object.entries(state.agents).map(([id,a]: any)=><section className="agent" key={id}><div className="agenthead"><div className={`avatar ${id}`}>{id.slice(-1)}</div><div><h2>{id}</h2><small><i className={a.connected?'online':'offline'}/>{a.connected?'In the arena':'Disconnected'}</small></div><span>{money(a.spent)}</span></div><div className="model">{a.model}</div><div className="action">{a.action}</div><div className="agentstats"><span><b>{a.contributions}</b> blocks placed</span><span><b>{state.tasks.filter((t:any)=>t.owner===id&&t.status==='done').length}</b> tasks complete</span></div><details><summary>Inventory · {Object.values(a.inventory).reduce((s:number,n:any)=>s+n,0)} items</summary><div className="inventory">{Object.entries(a.inventory).map(([name,count]:any)=><span key={name}>{name.replaceAll('_',' ')} <b>{count}</b></span>)}</div></details><p className="latest">{state.messages.filter((m:any)=>m.agent===id).slice(-1)[0]?.text||'Ready to collaborate.'}</p></section>)}</div>
    <div className="bottom"><section><div className="sectionhead"><h2>Task board</h2><span>{done} complete</span></div>{state.blueprint&&<p>{state.blueprint.design.description}</p>}<div className="tasks">{state.tasks.length?state.tasks.map((t:any)=><div className="task" key={t.id}><span className={`dot ${t.status}`}/><div><b>{t.label}</b><small>{t.error||`${t.blocks.length} blocks · ${t.owner||'unclaimed'}`}</small></div><span>{t.status}</span></div>):<div className="empty">The first blueprint will turn this board into construction tasks.</div>}</div></section><section><h2>Completion checks</h2><p>A house is finished when the world passes every check.</p><div className="checklist">{Object.entries(state.checklist).map(([name,pass])=><div key={name}><span className={pass?'pass':''}>{pass?'✓':'○'}</span>{name.replace(/([A-Z])/g,' $1').replace(/^./,s=>s.toUpperCase())}</div>)}</div><h2 className="logtitle">Team messages</h2><div className="messages">{state.messages.slice(-12).reverse().map((m:any,i:number)=><p key={i}><b>{m.agent}</b> {m.text}</p>)}</div></section></div><footer>LOCAL ARENA · Survival mechanics · Shared budget · Run {state.id.slice(0,8)}</footer>
  </main>;
}
createRoot(document.getElementById('root')!).render(<App/>);
